[package]
name = "bwt-rle-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
compio = { version = "0.14.0", "features" = ["macros"] }
futures = "0.3.31"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
inherits = "release"
debug = true
strip = false
