[package]
name = "bwt-rle-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
inherits = "release"
debug = true
strip = false
